# Generated by Django 2.1.5 on 2019-02-03 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='practice',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female')], default='M', max_length=2),
        ),
    ]
