# Generated by Django 2.1.5 on 2019-02-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190211_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profession',
            field=models.CharField(default='', max_length=254, null=True),
        ),
    ]
