# Generated by Django 2.1.5 on 2019-02-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('doctor_id', models.IntegerField()),
                ('book_date', models.DateField()),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('limit_date', models.DateTimeField(auto_now_add=True)),
                ('book_text', models.TextField()),
                ('status', models.CharField(choices=[('P', 'pending'), ('A', 'accepted'), ('R', 'rejected')], default='P', max_length=2)),
                ('pub_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
