# Generated by Django 2.1.5 on 2019-02-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='limit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
