# Generated by Django 2.1.5 on 2019-02-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_medication_problem_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='pub_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='pub_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='pub_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
